### PR TITLE
Added more html tag support in comment blocks

### PR DESCRIPTION
**Pull request by cemerson**
Added support for a few additional html tags in comments blocks:
- `<b></b>`
- `<i></i>`
- `<u></u>`
- `<s></s>`            
- `<li></li>`
- `<ul></ul>`

### CODE REVIEW

**Comment by no-stack-dub-sack** [comment]
@cemerson this looks good I think - can you add documentation for this to the README and add samples in the test project / write some [tests ](https://github.com/no-stack-dub-sack/apexdox-vs-code/pull/20#issuecomment-658339950) to cover this? This comment describes how to run the extension's tests: https://github.com/no-stack-dub-sack/apexdox-vs-code/pull/20#issuecomment-658339950

**Comment by cemerson** [comment]
My apologies but I’ve never wrote out tests for this kind of project – I only have experience with SFDC/Apex tests. I can try to hack something together eventually but if someone else is more skilled/able here feel free to jump in.

**Comment by no-stack-dub-sack** [comment]
@cemerson  If you're ok with it, I can take over this PR from here then and add the required tests. Sound ok? It may take me a bit of time to get to it, but hopefully sometime in the next week or so.

**Comment by cemerson** [comment]
Sure – no prob at all. 🙏🏻

**Comment by cemerson** [comment]
> @cemerson If you're ok with it, I can take over this PR from here then and add the required tests. Sound ok? It may take me a bit of time to get to it, but hopefully sometime in the next week or so.

BTW if/when you do get the time to add the tests and get a sec please share a link to where they are so I can review them for future reference. Or if it will be a while till you can get to this feel free to share a link to similar tests in this project and I'll review in case they feel like something I can add after all.

**Review by no-stack-dub-sack — APPROVED** [review]
Thanks @cemerson, and sorry for the long delay! I've finished up the work on this branch and it will be merged and included in the next release (which should be imminent). Thanks again for getting the ball rolling on this - a cool addition!

**Pull request merged**
