### PR TITLE
Add tag return and deprecate returns

### LINKED ISSUE #19: Allow @return token (without 's')
Hi Peter,

Thanks for this really useful plugin, I appreciate it.

I'm wondering if you found any particular issue with the token **@return**, as you renamed it to **@returns** ~1 year ago.

If your point was to solely make it consistent with TypeDoc (and consequently your Typescript docblocks), that'd make sense if Salesforce didn't seem to recommend **@return** as part of [ApexDoc](https://github.com/SalesforceFoundation/ApexDoc).

Moreover, PMD also takes ApexDoc as its source of truth of the documentation part for Apex code analysis, which makes ApexDox snippets for Apex methods always leaving us with the issue:

```
Missing ApexDoc @return (rule: Documentation-ApexDoc)apex pmdApexDoc
```

Is there any chance to revert it back to the singular version, or maybe accept both when html docs are generated?

FWIW, you can find PMD's ApexDocRule [here](https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/documentation/ApexDocRule.java).

Happy to work on a PR if you want it.

Thank you

### PR DESCRIPTION
**Pull request by berardo**
Rename the tag **@returns** to **@return**

That's the initial idea, but I still haven't had time to test it myself

closes #19

### CODE REVIEW

**Comment by berardo** [comment]
Faced a few issues trying to run tests.
Please advise how to proceed with that.

Thanks

**Comment by no-stack-dub-sack** [comment]
You can test in a coupe of ways - are you talking about running the test suite or just testing your changes locally?

**Comment by no-stack-dub-sack** [comment]
Hey @berardo, just checking in! Def no rush, as I realize I dropped the ball and getting back to you quickly the first time around. Also, if you've become busy, I can finish out the requested changes if that's easier. Let me know what works best for you. 

Thanks again!

**Comment by no-stack-dub-sack** [comment]
@berardo this PR was merged via #25 today and will be released shortly. Thanks again for your contribution here!

**Pull request merged**
