### PR TITLE
Fix closing h2 tag to h3

### PR DESCRIPTION
**Pull request by dschach**
The generator has the wrong closing tag on subsection h2 tags, which is causing prettier verification runs to fail. Updating those for proper html markup.

This is a great extension - thanks for making it!

### CODE REVIEW

**Comment by dschach** [comment]
Also, please consider renaming the `master` branch to `main`. Thank you!

**Comment by no-stack-dub-sack** [comment]
@dschach nice catch! And apologies for the late reply. Honestly I'm considering archiving this repo since there really isn't a whole lot of activity and probably not that many active users. I will try to get around to releasing this fix this week if I can.

**Comment by dschach** [comment]
Please don't archive it!
Or at least transfer it to me so I can maintain it. I'd like to see it run
from command line so dox can be created via GitHub actions, etc.
It's so much better than CParra's docs generator, I think.


Sent via mobile. Please excuse brevity.

**Comment by no-stack-dub-sack** [comment]
Actually, while there's been very few issues filed against this repo, that's been the most common request. I've tried to get those that have requested it to contribute to no avail 🙁 (see #11)

If this is something you'd be open to helping out with I'd also love to see this happen. I think right now the main challenge is how intertwined the VS Code API is with a lot of the code.

**Comment by no-stack-dub-sack** [comment]
@dschach the extension tests are failing on my end... for the changes in the test snapshots (HTML files), did you manually change these or did you run `yarn update-snapshots`? If you manually changed them, can you please run the extension tests (they should be failing due to a whitespace diff - the HTML indentation was wrong because of the mismatched closing tag), then run `yarn update-snapshots`, then run the tests again and make sure they pass? If so, commit and push up the changes and then I can merge / publish.

Run tests here:

image

Thanks!

**Comment by dschach** [comment]
Having trouble with this - it's my first time working with a VSCode Extension in VSCode. I'm used to Salesforce only projects. I'll let you know how I'm getting along. @no-stack-dub-sack

**Comment by no-stack-dub-sack** [comment]
@dschach no problem, if you don't have the time and would like me to finish it off, feel free to re-open the PR in it's original state and I can take it from there.

**Comment by dschach** [comment]
I've clearly screwed up something, so I'm opening a new PR. I'm also updating dependabot alerts.
I'd like to learn how to get it set up, but every time I run something, it gives me an error. I'll get back to you.
Maybe we can set up a call. For now, I'm going to keep trying to get yarn to work, all the dependencies up to date, and the test stuff to go without a hitch.

**Comment by dschach** [comment]
@no-stack-dub-sack node-static is a local web server with lots of security problems. I'm looking for an alternative.

**Pull request closed without merging**
